# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from so101_lab.transport import ppo_pb2 as so101__lab_dot_transport_dot_ppo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in so101_lab/transport/ppo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PPOTrainingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ready = channel.unary_unary(
                '/ppo_transport.PPOTraining/Ready',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
                _registered_method=True)
        self.Init = channel.stream_unary(
                '/ppo_transport.PPOTraining/Init',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.InitResponse.FromString,
                _registered_method=True)
        self.SampleAction = channel.stream_unary(
                '/ppo_transport.PPOTraining/SampleAction',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.ActionResult.FromString,
                _registered_method=True)
        self.SendStepResult = channel.stream_unary(
                '/ppo_transport.PPOTraining/SendStepResult',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
                _registered_method=True)
        self.RunPPOUpdate = channel.stream_unary(
                '/ppo_transport.PPOTraining/RunPPOUpdate',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.UpdateMetrics.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/ppo_transport.PPOTraining/SetMode',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.ModeRequest.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
                _registered_method=True)
        self.SampleActionDeterministic = channel.stream_unary(
                '/ppo_transport.PPOTraining/SampleActionDeterministic',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.ActionResult.FromString,
                _registered_method=True)
        self.ResetPolicy = channel.unary_unary(
                '/ppo_transport.PPOTraining/ResetPolicy',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.stream_unary(
                '/ppo_transport.PPOTraining/SaveCheckpoint',
                request_serializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
                response_deserializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
                _registered_method=True)


class PPOTrainingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ready(self, request, context):
        """Lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SampleAction(self, request_iterator, context):
        """Per rollout step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStepResult(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPPOUpdate(self, request_iterator, context):
        """After rollout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Eval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SampleActionDeterministic(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request_iterator, context):
        """Checkpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PPOTrainingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
            ),
            'Init': grpc.stream_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.InitResponse.SerializeToString,
            ),
            'SampleAction': grpc.stream_unary_rpc_method_handler(
                    servicer.SampleAction,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.ActionResult.SerializeToString,
            ),
            'SendStepResult': grpc.stream_unary_rpc_method_handler(
                    servicer.SendStepResult,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
            ),
            'RunPPOUpdate': grpc.stream_unary_rpc_method_handler(
                    servicer.RunPPOUpdate,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.UpdateMetrics.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.ModeRequest.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
            ),
            'SampleActionDeterministic': grpc.stream_unary_rpc_method_handler(
                    servicer.SampleActionDeterministic,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.ActionResult.SerializeToString,
            ),
            'ResetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPolicy,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
            ),
            'SaveCheckpoint': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=so101__lab_dot_transport_dot_ppo__pb2.DataChunk.FromString,
                    response_serializer=so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ppo_transport.PPOTraining', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ppo_transport.PPOTraining', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PPOTraining(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppo_transport.PPOTraining/Ready',
            so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ppo_transport.PPOTraining/Init',
            so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SampleAction(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ppo_transport.PPOTraining/SampleAction',
            so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStepResult(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ppo_transport.PPOTraining/SendStepResult',
            so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPPOUpdate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ppo_transport.PPOTraining/RunPPOUpdate',
            so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.UpdateMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppo_transport.PPOTraining/SetMode',
            so101__lab_dot_transport_dot_ppo__pb2.ModeRequest.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SampleActionDeterministic(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ppo_transport.PPOTraining/SampleActionDeterministic',
            so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ppo_transport.PPOTraining/ResetPolicy',
            so101__lab_dot_transport_dot_ppo__pb2.Empty.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ppo_transport.PPOTraining/SaveCheckpoint',
            so101__lab_dot_transport_dot_ppo__pb2.DataChunk.SerializeToString,
            so101__lab_dot_transport_dot_ppo__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
